/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_AHB1ENR   (*(volatile uint32_t *)0x40023830U)

#define GPIOA_MODER   (*(volatile uint32_t *)0x40020000U)
#define GPIOA_ODR     (*(volatile uint32_t *)0x40020014U)

#define GPIOAEN       (1U << 0)
#define PA5           (1U << 5)

static void delay(void)
{
    for (volatile uint32_t i = 0; i < 500000U; i++)
    {
        /* simple delay */
    }
}

int main(void)
{
    /* 1. Enable GPIOA clock */
    RCC_AHB1ENR |= GPIOAEN;

    /* 2. Configure PA5 as General Purpose Output */
    GPIOA_MODER &= ~(3U << 10);
    GPIOA_MODER |=  (1U << 10);

    while (1)
    {
        /* 3. LED ON */
        GPIOA_ODR |= PA5;

        delay();

        /* 4. LED OFF */
        GPIOA_ODR &= ~PA5;

        delay();
    }
}
